export const JOBS = [
  { name: "仲居", link: "nakai" },
  { name: "フロント・ベル", link: "front" },
  { name: "レストランホール", link: "restaurant-staff" },
  { name: "業務全般", link: "generalist" },
  { name: "清掃（ハウスキーピング）", link: "house-keeping" },
  { name: "調理補助", link: "food-preparation-assistance" },
  { name: "プール・マリン業務", link: "pool" },
  { name: "飲食店", link: "dinning-room" },
  { name: "調理（コック）", link: "cook" },
  { name: "裏方", link: "propman" },
  { name: "ナイトワーク", link: "hostess" },
  { name: "テーマパーク", link: "theme-park" },
  { name: "マリンスタッフ", link: "marine-staff" },
  { name: "スキー場スタッフ（リフト係）", link: "lift" },
  { name: "カフェ・喫茶店スタッフ", link: "cafe" },
  { name: "マッサージ", link: "massage" },
  { name: "ラウンジ", link: "lounge" },
  { name: "予約事務", link: "booking-office" },
  { name: "洗い場スタッフ", link: "wash-place" },
  { name: "ブライダル", link: "bridal" },
  { name: "農業・酪農", link: "agriculture" },
  { name: "工場スタッフ", link: "factory" },
  { name: "その他業種", link: "others" },
];